magic
this

Run upptime/uptime-monitor@v1.41.4
  with:
    command: update-template
  env:
    GH_PAT: ***
(node:2322) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:2322) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.

🔼 Upptime @v1.41.5
GitHub-powered open-source uptime monitor and status page by Anand Chowdhary

* Source: https://redirect.github.com/upptime/upptime
* Docs and more: https://upptime.js.org
* More by Anand Chowdhary: https://anandchowdhary.com

Removed legacy .github/workflows
Added new .github/workflows
Removed template files
Removed old data from api
Removed old data from graphs
Removed old data from history
ERROR Error: To https://github.com/472ethan/status
 ! [remote rejected] master -> master (refusing to allow a GitHub App to create or update workflow `.github/workflows/graphs.yml` without `workflows` permission)
error: failed to push some refs to 'https://github.com/472ethan/status'

    at runGit (/home/runner/work/_actions/upptime/uptime-monitor/v1.41.4/webpack:/@upptime/uptime-monitor/dist/helpers/git.js:11:1)
    at push (/home/runner/work/_actions/upptime/uptime-monitor/v1.41.4/webpack:/@upptime/uptime-monitor/dist/helpers/git.js:23:1)
    at updateTemplate (/home/runner/work/_actions/upptime/uptime-monitor/v1.41.4/webpack:/@upptime/uptime-monitor/dist/update-template.js:83:1)
Error: To https://github.com/472ethan/status
 ! [remote rejected] master -> master (refusing to allow a GitHub App to create or update workflow `.github/workflows/graphs.yml` without `workflows` permission)
error: failed to push some refs to 'https://github.com/472ethan/status'

dealt with magic....

https://redirect.github.com/upptime/upptime/issues/995#issuecomment-2327707163

(what the fuck github???)